[project]
name = "pyoa"
version = "0.1.0"
description = "Ürrhghtücrrhigtph gd igtbigtrrhigt aon bughtum"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pylirecouleur>=0.0.5",
    "typer>=0.21.1",
]

[project.scripts]
pyoa = "pyoa.cli:main"

[tool.uv]
package = true
